version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Create symlink to role
          command: |
            mkdir -p "${HOME}/.ansible/roles" && \
            ln -s "${HOME}/project" "${HOME}/.ansible/roles/ansible-role-tinypilot"
      - run:
          name: Create Python3 virtual environment
          command: python3 -m venv venv
      - run:
          name: Test role with molecule
          command: |
            . venv/bin/activate && \
            pip install --upgrade pip && \
            pip install ansible==2.9.10 && \
            pip install docker==4.2.2 molecule[lint]==3.0.6 molecule[docker]==3.0.6 && \
            ansible-galaxy install --role-file molecule/default/requirements.yml && \
            ansible --version && \
            molecule --version && \
            molecule test
workflows:
  version: 2
  all-tests:
    jobs:
      - build